config/routes.rb
UserArticleComments::Application.routes.draw do
  get "home/index"
resources :users do
resources :articles 
end
resources :articles do 
resources :comments 
end
resources :comments do
  collection do
  get 'approve'
  end
end 
resources :contacts

 root :to => "articles#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
   has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" },
     :storage => :s3,
     :s3_credentials => "#{RAILS_ROOT}/config/s3.yml",
     :bucket => "sharmanyros",
      :path => "/sriram/images/:style/:id/:filename" ;
  has_attached_file :file,
      :storage => :s3,
      :s3_credentials => "#{RAILS_ROOT}/config/s3.yml",
      :bucket => "sharmanyros",
      :path => "/sriram/files/:style/:id/:filename" ;
  def self.per_page
       10
      end



end

app/models/ckeditor/asset.rb
require 'mime/types'

class Ckeditor::Asset < ActiveRecord::Base
  set_table_name "ckeditor_assets"
  
  belongs_to :user
  belongs_to :assetable, :polymorphic => true
  
  before_validation :make_content_type
  before_create :read_dimensions, :parameterize_filename
  
  attr_accessible :data, :assetable_type, :assetable_id
  
  def url(*args)
    data.url(*args)
  end
  alias :public_filename :url
  
  def filename
    data_file_name
  end
  
  def content_type
    data_content_type
  end
  
  def size
    data_file_size
  end
  
  def path
    data.path
  end
  
  def styles
    data.styles
  end
  
  def format_created_at
    I18n.l(created_at, :format=>"%d.%m.%Y %H:%M")
  end
  
  def to_xml(options = {})
    builder = options[:builder] ||= Nokogiri::XML::Builder.new(options)

    builder.send(self.type.to_s.downcase) do |xml|
      xml.id_ self.id
      xml.filename self.filename
      xml.size self.size
      xml.path self.url
      
      xml.styles do
        self.styles.each do |style|
          xml.send(style.first, self.url(style.first))
        end
      end unless self.styles.empty?
    end
    
    builder.to_xml
  end
  
  def has_dimensions?
    respond_to?(:width) && respond_to?(:height)
  end
  
  def image?
    Ckeditor::IMAGE_TYPES.include?(data_content_type)
  end
  
  def geometry
    @geometry ||= Paperclip::Geometry.from_file(data.to_file)
    @geometry
  end
  
  protected
    
    def parameterize_filename
      unless data_file_name.blank?
        filename = Ckeditor::Utils.parameterize_filename(data_file_name)
        self.data.instance_write(:file_name, filename)
      end  
    end
    
    def read_dimensions
      if image? && has_dimensions?
        self.width = geometry.width
        self.height = geometry.height
      end
    end
    
    def make_content_type
      if data_content_type == "application/octet-stream"
        content_types = MIME::Types.type_for(filename)
        self.data_content_type = content_types.first.to_s unless content_types.empty?
      end
    end
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than=>100.megabytes
  
  def url(*args)
    if [:thumb, :content].include?(args.first)
      send("url_#{args.first}")
    else
      data.url(*args)
    end
  end
  
  def url_content
	  data.url
	end
	
	def url_thumb
	  extname = File.extname(filename)
    
    case extname.to_s
      when '.swf' then '/javascripts/ckeditor/images/swf.gif'
      when '.pdf' then '/javascripts/ckeditor/images/pdf.gif'
      when '.doc', '.txt' then '/javascripts/ckeditor/images/doc.gif'
      when '.mp3' then '/javascripts/ckeditor/images/mp3.gif'
      when '.rar', '.zip', '.tg' then '/javascripts/ckeditor/images/rar.gif'
      when '.xls' then '/javascripts/ckeditor/images/xls.gif'
      else '/javascripts/ckeditor/images/ckfnothumb.gif'
    end
	end
	
	def to_json(options = {})
	  options[:methods] ||= []
	  options[:methods] << :url_content
	  options[:methods] << :url_thumb
	  super options
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
	                  :styles => { :content => '575>', :thumb => '80x80#' }
	
	validates_attachment_size :data, :less_than=>2.megabytes
	
	def url_content
	  url(:content)
	end
	
	def url_thumb
	  url(:thumb)
	end
	
	def to_json(options = {})
	  options[:methods] ||= []
	  options[:methods] << :url_content
	  options[:methods] << :url_thumb
	  super options
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
def index
 @user = User.find(2)
 @articles = @user.articles.paginate(:page =>params[:page], :per_page => 5) 

 end
 
def new
    @user = User.find(2)
    @article = @user.articles.new
     render :action => "new"
  end
  
def create
    @user = User.find(2)
   
    @article = @user.articles.create(params[:article])
    render :action => "show"
     end
     
def show
    @user = User.find(2)
    @article = @user.articles.find(params[:id])
    render :action => "show"
  end


 
 
  def update
    @user = User.find(params[:id])
    @article = @user.articles.find(params[:id])
      if @user.articles.update_attributes(params[:article])
        redirect_to(@articles, :notice => 'article was successfully updated.')   
      else
        render :action => "edit" 
      
      
    end
  end
  
def destroy
    @user = User.find(params[:user_id])
    @article = @user.articles.find(params[:id])
    @article.destroy
    redirect_to(articles_url)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def index
 @comment = Comment.find(:id)


 end
def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(params[:comment])
  
    if @comment.save
    Admin.admin_approval(@comment).deliver
   end

   redirect_to article_path(@article)
  end
 
 def approve
 
 #render :text => params.inspect and return
 @comment = Comment.find(params[:cid])
 @comment.update_attributes(:approve => params[:approve])

render :text => "Done" and return
 
 end
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
def index
render :action => "index"
end
def new


end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.all
      render :action => "index"
  end

  def show
    @user = User.find(params[:id])
    render :action => "show"
  end

  def new
    @user = User.new
     render :action => "new"
  end


  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
   
      if @user.save
       redirect_to(@user, :notice => 'user was successfully created.')
      else
    render :action => "new"    
      end
    
  end


  def update
    @user = User.find(params[:id])
    
      if @user.update_attributes(params[:user])
        redirect_to(@user, :notice => 'user was successfully updated.')   
      else
        render :action => "edit" 
      
      
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

   
     redirect_to(users_url) 
 
    end
 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_admin_approval.html.erb
<!DOCTYPE html>
<html>
<head>
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
</head>
<body>
<%= form_for([@article, @article.comments.build]) do |f| %>
<center>
  <table border=0 >
  <tr bg color =#A0C500>
    <td> <font color="white"><%= f.label :commenter %></font></td>
    <td><%= f.text_field :commenter %></td>
  </tr>
  <tr bg color =#A0C500>
    <td> <font color="white"><%= f.label :comment %></font></td>
    <td><%= f.text_area :comment %></td>
  </tr>
  <table>
  <div class="actions">
    <%= f.submit %>
  </div>
  </center>
<% end %>




</body>
</html>

app/views/admin/admin_approval.html.erb
<!DOCTYPE html>
<html>
<head>
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
</head>
<body>
<h3><%= @comment.comment %></h3>
<h5>is commented by:</h5>
<h4><%= @comment.commenter %></h4>
<%= link_to "approved", "http://172.20.1.65:3000/comments/approve?cid=#{@comment.id}&approve=1" %>&nbsp;&nbsp;&nbsp;
<%= link_to "Not approved","http://172.20.1.65:3000/comments/approve?cid=#{@comment.id}&approve=0" %>
 
 

</body>
</html>

app/views/articles/_article.html.erb
<h1><font color="white">Listing Articles</font></h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user.articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>

</table>

<br />

<font color="yellow"><%= link_to 'New Article',  %></font>

app/views/articles/_form.html.erb
<%= form_for([@user, @user.articles.build],:html => { :multipart => true }) do |f| %>
  <div class="field">
    <font color="white"><%= f.label :title %></font><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <font color="white"><%= f.label :description %></font><br />
    <%= f.ckeditor_textarea( 'article', 'description',:toolbarSet => 'Simple', :width => '100%', :height => '200px') %> 
  </div>
  <div>
   <%= f.file_field :avatar %>
 
  </div>
  <div>
   <%= f.file_field :file %>
 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1><font color="white">Editing user</font></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', Users_path %>

app/views/articles/index.html.erb
<center>
<h1><font color="white">Listing articles</font></h1>


 
<% @articles.each do |article| %>

<center>
  <table border=1>
  <tr bgcolor=		#A0C544>
  <td width="500" height="50"><%= link_to "#{article.title}",article %> |<i>by</i>:<%=@user.username %>| <i>on:</i> <%= article.created_at.strftime("%Y-%m-%d") %></td>
  </tr>
  <tr bgcolor=	#A0C544>
  <td width="500" height="70"><%= sanitize(truncate("#{article.description}", :length=> 30)) %> </td>
  </tr>
  <tr>
 
  <td><%= article.avatar_file_name %></td>
  </tr>
  <tr>
 
  <td><%= article.file_file_name %></td>
  </tr>
  </table>
  </center>
  <br/>
  
 <%#= link_to "more details..." , article %>
  <% end %>
  <%= will_paginate @articles, :param_name =>'page' %>
<br />
<center>

<font color="yellow"><%= link_to 'New Article', new_user_article_path(:user_id => 2) %></font>

app/views/articles/new.html.erb
<h1><font color="white">New Article</font></h1>

<%= render 'form' %>

<font color="yellow"><%= link_to 'Back', user_articles_path %></font>

app/views/articles/show.html.erb
<%= link_to 'Back', user_articles_path(:user_id=>2) %>
<center>
<marquee bgcolor="black" behaviour="alternate">
<font color="yellow"> Please comment your opinion on this article......</font>
</marquee>
<h1><font color="white"><%= @article.title %></font></h1><font color="white"><i>by :</i><%= @user.username %></font>


<font color="red"><%= link_to "download", @article.file.url %></font>
<br/>
<table border = 0>
<tr bgcolor=	#A0C544>
  <td width="500" height="250"><%= sanitize(@article.description) %></font> </td>
 
</tr>
</table>
<h2><font color="white"><blink>Comments</blink></font></h2>
<% @article.comments.each do |comment| %>
<% if comment.approve == 1 %>
 
    <font color="orange"><%= comment.commenter %>:</font>
    <font color="white"><%= comment.comment %></font>
    <font color="white"><i>on:</i><%= comment.created_at.strftime("%Y-%m-%d") %></font>
    <br/>
 <% end %>
<% end %>
<h2><font color="green">Add a comment:</font></h2>

<%= form_for([@article, @article.comments.build]) do |f| %>
<center>
  <table border=0 >
  <tr bg color =#A0C500>
    <td> <font color="white"><%= f.label :commenter %></font></td>
    <td><%= f.text_field :commenter %></td>
  </tr>
  <tr bg color =#A0C500>
    <td> <font color="white"><%= f.label :comment %></font></td>
    <td><%= f.text_area :comment %></td>
  </tr>
  <table>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  </center>
<% end %>

app/views/contacts/_form.html.erb
<%= form_tag %>
  <div class="field">
    <font color="white"><%= label_tag :fullname %></font><br />
    <%= text_field_tag :fullname %>
  </div>
  <div class="field">
    <font color="white"><%= label_tag :mail %></font><br />
    <%= text_field_tag :mail %>
  </div>
  <div class="field">
    <font color="white"><%= label_tag :inquiry %></font><br />
    <%= text_area_tag :inquiry %>
  </div>
  <div class="actions">
    <%= submit_tag "submit"%>
  </div>

app/views/contacts/index.html.erb
<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1><font color="white">Contact Us</font></h1>

<%= render 'form' %>

<font color="yellow"><%#= link_to 'Back', user_articles_path %></font>

app/views/home/index.html.erb
<center>
<h1> Articles </h1>
<%= link_to "User Articles", user_articles_path(:user_id => 2) %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserArticleComments</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag :ckeditor %>

  <%= csrf_meta_tag %>
</head>



<body background="/images/blac2.png">
<center><h1><font color="green">ARTICLES</font></h1></center>
<table width="1000" height="15">
<tr>
<td bgcolor="gray" width="250" align=center><b><%= link_to "HOME"  %></b></td>
<td bgcolor="gray" width="250" align=center><b><%= link_to "CONTACT US", contacts_path  %></b></td>
<td bgcolor="gray" width="250" align=center><b><%= link_to "ORDER NOW"  %></b></td>
<td bgcolor="gray" width="250" align=center><b><%= link_to "PUBLISHERS"  %></b></td>
</tr>
</table>
<hr>

<%= yield %>
<hr>
<center><h5><font color="aqua">copyright :@articles 2011</font></h5></center>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  
 <table border=1>
 <tr bgcolor="black">
    <td><font color="white"><%= f.label :username %></font></td>
    <td><font color="white"><%= f.text_field :username %></font></td>
  </tr>
  <tr bgcolor="black">
     <td><font color="white"><%= f.label :email %></font></td>
     <td><font color="white"><%= f.text_field :email %></font></td>
  </tr>
  <tr bgcolor="black
  ">
     <td><font color="white"><%= f.label :address %></font></td>
     <td><font color="white"><%= f.text_area :address %></font></td>
  </tr>
  </table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><font color="white">Editing user</font></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', Users_path %>

app/views/users/index.html.erb
<h1><font color="white">Listing users</font></h1>

<table>
  <tr>
    <th>Username</th>
    <th>email</th>
    <th>address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.address %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<font color="yellow"><%= link_to 'New Article', user_articles_path %></font>

app/views/users/new.html.erb
<h1><font color="white">New User</font></h1>

<%= render 'form' %>

<font color="yellow"><%= link_to 'Back', users_path %></font>

app/views/users/show.html.erb
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>
<p>
  <b>Address:</b>
  <%= @user.address %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>